[package]
name = "engine-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.3"
cliclack = "0.3.7"
console = "0.16.2"
minijinja = "2.14.0"
rust-embed = "8.11.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"

[dev-dependencies]
tempfile = "3.24.0"
