[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
cargo_metadata = "0.23.1"
clap = { version = "4.5.54", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter"] }
syn = { version = "2.0.114", features = ["full"] }
thiserror = "2.0.18"
walkdir = "2.5.0"
