[package]
name = "engine-rs"
version = "0.1.0"
edition = "2024"
description = "engine.rs scaffolding"
license = "MIT"
readme = "README.md"

[dependencies]
engine-rs-lib = { "path" = "../lib" }
blake3 = "1.8"
cliclack = "0.3"
console = "0.16"
minijinja = "2.14"
rust-embed = "8.11"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
loom = { version = "0.7", optional = true }
clap = { version = "4.5.54", features = ["derive"] }
serde_json = "1.0.149"

[dev-dependencies]
tempfile = "3.24"

[features]
loom = ["dep:loom"]
