[package]
name = "engine-rs"
version = "0.1.0"
edition = "2024"
description = "engine.rs scaffolding"
license = "MIT"
readme = "README.md"

[dependencies]
engine-rs-lib = { "path" = "../lib" }
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
cliclack = "0.3.7"
console = "0.16.2"
toml = "0.9.11"

[dev-dependencies]
assert_cmd = { version = "2.1", features = ["color"] }
insta = { version = "1.46.1", features = ["glob"] }
tempfile = "3.24"
walkdir = "2.5.0"
