[package]
name = "engine-rs"
version = "0.1.0"
edition = "2024"
description = "engine.rs scaffolding"
license = "MIT"
readme = "README.md"

[dependencies]
engine-rs-lib = { "path" = "../lib" }
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
cliclack = "0.3.7"
console = "0.16.2"
toml = "1.0.1"
rust-embed = "8.11.0"

[dev-dependencies]
assert_cmd = { version = "2.1", features = ["color"] }
assert_fs = { version = "1.1.3", features = ["color", "color-auto"] }
color-eyre = "0.6.5"
ctor = "0.6.3"
insta = { version = "1.46.1", features = ["glob"] }
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter"] }
minijinja = "2.14.0"
predicates = "3.1.3"
tempfile = "3.24"
thiserror = "2.0.18"
walkdir = "2.5.0"
